// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4zVjGR4wDk8e3NhuU_Frje7jq7ysRFsk',
    appId: '1:555238392596:web:4ab51dcc96c180aa163801',
    messagingSenderId: '555238392596',
    projectId: 'activ-923a4',
    authDomain: 'activ-923a4.firebaseapp.com',
    storageBucket: 'activ-923a4.firebasestorage.app',
    measurementId: 'G-W2P0TVBK5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQrmwa27kVd40258k74h7zFOhEfr1gCDk',
    appId: '1:555238392596:android:98e85a22f842eaee163801',
    messagingSenderId: '555238392596',
    projectId: 'activ-923a4',
    storageBucket: 'activ-923a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDik2ty9DnExNBlZ86O5xa0pMwWh5z76s',
    appId: '1:555238392596:ios:b30fa9c1dc5e855a163801',
    messagingSenderId: '555238392596',
    projectId: 'activ-923a4',
    storageBucket: 'activ-923a4.firebasestorage.app',
    iosBundleId: 'com.example.projectactiv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDik2ty9DnExNBlZ86O5xa0pMwWh5z76s',
    appId: '1:555238392596:ios:b30fa9c1dc5e855a163801',
    messagingSenderId: '555238392596',
    projectId: 'activ-923a4',
    storageBucket: 'activ-923a4.firebasestorage.app',
    iosBundleId: 'com.example.projectactiv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4zVjGR4wDk8e3NhuU_Frje7jq7ysRFsk',
    appId: '1:555238392596:web:0af8d19fe2928c22163801',
    messagingSenderId: '555238392596',
    projectId: 'activ-923a4',
    authDomain: 'activ-923a4.firebaseapp.com',
    storageBucket: 'activ-923a4.firebasestorage.app',
    measurementId: 'G-F4M2ZHVFCT',
  );
}
